import { DomainInvariantError } from "./domainErrors";

export const DISTRIBUTION_STATES = [
  "DRAFT",
  "SUBMISSION_LOCKED",
  "SNAPSHOT_CREATED",
  "VALIDATION_PENDING",
  "VALIDATED",
  "APPROVAL_PENDING",
  "APPROVED",
  "REJECTED",
  "METADATA_GENERATED",
  "PACKAGE_BUILT",
  "PACKAGE_VERIFIED",
  "DISTRIBUTION_JOB_CREATED",
  "PROVIDER_SELECTED",
  "AUTHENTICATING_PROVIDER",
  "UPLOAD_IN_PROGRESS",
  "SUBMITTED_TO_PROVIDER",
  "PROVIDER_PROCESSING",
  "DSP_ACCEPTED",
  "DSP_LIVE",
  "CATALOG_ACTIVE",
  "ROYALTY_READY",
  "ROYALTY_IMPORTED",
  "PAYMENT_PROCESSING",
  "STATEMENT_GENERATED",
  "RELEASE_ARCHIVED",
  "CANCELLED",
  "TAKEDOWN_PENDING",
  "TAKEDOWN_COMPLETED",
] as const;

export type DistributionState = (typeof DISTRIBUTION_STATES)[number];

const ALLOWED_TRANSITIONS: ReadonlyMap<DistributionState, readonly DistributionState[]> = new Map([
  ["DRAFT", ["SUBMISSION_LOCKED", "CANCELLED"]],
  ["SUBMISSION_LOCKED", ["SNAPSHOT_CREATED", "CANCELLED"]],
  ["SNAPSHOT_CREATED", ["VALIDATION_PENDING", "CANCELLED"]],
  ["VALIDATION_PENDING", ["VALIDATED", "REJECTED", "CANCELLED"]],
  ["VALIDATED", ["APPROVAL_PENDING", "REJECTED", "CANCELLED"]],
  ["APPROVAL_PENDING", ["APPROVED", "REJECTED", "CANCELLED"]],
  ["APPROVED", ["METADATA_GENERATED", "CANCELLED"]],
  ["METADATA_GENERATED", ["PACKAGE_BUILT", "CANCELLED"]],
  ["PACKAGE_BUILT", ["PACKAGE_VERIFIED", "CANCELLED"]],
  ["PACKAGE_VERIFIED", ["DISTRIBUTION_JOB_CREATED", "CANCELLED"]],
  ["DISTRIBUTION_JOB_CREATED", ["PROVIDER_SELECTED", "CANCELLED"]],
  ["PROVIDER_SELECTED", ["AUTHENTICATING_PROVIDER", "CANCELLED"]],
  ["AUTHENTICATING_PROVIDER", ["UPLOAD_IN_PROGRESS", "CANCELLED"]],
  ["UPLOAD_IN_PROGRESS", ["SUBMITTED_TO_PROVIDER", "CANCELLED"]],
  ["SUBMITTED_TO_PROVIDER", ["PROVIDER_PROCESSING", "CANCELLED"]],
  ["PROVIDER_PROCESSING", ["DSP_ACCEPTED", "REJECTED", "CANCELLED"]],
  ["DSP_ACCEPTED", ["DSP_LIVE", "TAKEDOWN_PENDING"]],
  ["DSP_LIVE", ["CATALOG_ACTIVE", "TAKEDOWN_PENDING"]],
  ["CATALOG_ACTIVE", ["ROYALTY_READY", "TAKEDOWN_PENDING"]],
  ["ROYALTY_READY", ["ROYALTY_IMPORTED", "TAKEDOWN_PENDING"]],
  ["ROYALTY_IMPORTED", ["PAYMENT_PROCESSING", "TAKEDOWN_PENDING"]],
  ["PAYMENT_PROCESSING", ["STATEMENT_GENERATED", "TAKEDOWN_PENDING"]],
  ["STATEMENT_GENERATED", ["RELEASE_ARCHIVED", "TAKEDOWN_PENDING"]],
  ["RELEASE_ARCHIVED", []],
  ["CANCELLED", []],
  ["TAKEDOWN_PENDING", ["TAKEDOWN_COMPLETED"]],
  ["TAKEDOWN_COMPLETED", []],
  ["REJECTED", []],
]);

export class DistributionStateMachine {
  canTransition(previous: DistributionState, next: DistributionState): boolean {
    return ALLOWED_TRANSITIONS.get(previous)?.includes(next) ?? false;
  }

  assertTransition(previous: DistributionState, next: DistributionState): void {
    if (!this.canTransition(previous, next)) {
      throw new DomainInvariantError("Invalid distribution state transition", { previous, next });
    }
  }

  isTerminal(state: DistributionState): boolean {
    return ["RELEASE_ARCHIVED", "CANCELLED", "TAKEDOWN_COMPLETED", "REJECTED"].includes(state);
  }
}

